[package]
name = "icylauncher"
version = "0.1.0"
edition = "2021"

[dependencies]
freedesktop-desktop-entry = "0.7.5"
iced = { version = "0.13.1", features = ["image"] }
iced_layershell = "0.13.0"
iced_runtime = "0.13.2"
